FROM node:20-alpine

WORKDIR /http-app

COPY ./package.json ./package.json

RUN npm install 

COPY ./tsconfig.json ./tsconfig.json

COPY ./src ./src

RUN npm run build


# check about this command

CMD ["node", "dist/index.js"]

