FROM node:20-alpine

WORKDIR /frontend

COPY ./package.json ./package.json

RUN npm install 

COPY ./tsconfig.json ./tsconfig.json

COPY ./app ./app

COPY ./public ./public

RUN npm run build


# check about this command

CMD ["npm", "start"]

